# app/ui/theme/colors.py


class Colors:
    BACKGROUND = "#F6F8FB"
    SURFACE = "#FFFFFF"
    SURFACE_SECONDARY = "#F0F4F9"
    BORDER = "#E3E8EF"

    TEXT_PRIMARY = "#1F2A37"
    TEXT_SECONDARY = "#5B6B7C"

    ACCENT = "#4C6EF5"

    STATUS_AAPPRENDRE_BG = "#E7F0FA"
    STATUS_AAPPRENDRE_TEXT = "#2F5C8F"

    STATUS_ACQUISE_BG = "#E6F4EE"
    STATUS_ACQUISE_TEXT = "#2E7D5A"

    SIDEBAR_BG = "#F3F6FA"
    SIDEBAR_HOVER = "#EDF2F8"
    SIDEBAR_ACTIVE_BG = "#E7F0FA"
    SIDEBAR_ACTIVE_TEXT = ACCENT

    BUTTON_PRIMARY_BG = ACCENT
    BUTTON_PRIMARY_HOVER = "#3F5CE6"
    BUTTON_PRIMARY_PRESSED = "#364FC7"
    BUTTON_PRIMARY_DISABLED_BG = "#E3E8EF"
    BUTTON_PRIMARY_DISABLED_TEXT = "#9AA7B4"

    BUTTON_SECONDARY_BG = "#FFFFFF"
    BUTTON_SECONDARY_BORDER = BORDER
    BUTTON_SECONDARY_TEXT = TEXT_PRIMARY